algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025

var
a, l, p: real

inicio
escreval("digite o lado do quadrado")
leia(l)

a <- l^2
escreval("a area do quadrado é ", a)

p <- 4*l
escreval("o perimetro do quadrado é ", p)

fimalgoritmo