algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025cal
var

r, h, v: inteiro

inicio

inicio
escreval("digite o raio e altura da lata de oleo")
leia(r)
leia(h)

v <- 3.14*r^2*h

escreval("o volume da lata é ", v) 



fimalgoritmo