algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025
var

a, r, p: real

inicio
escreval("digite o raio da circuferencia")
leia(r)

a <- 3.14*(r^2)
escreval("a area da circuferencia é ", a)

p <- 2*3.14*r
escreval("o perimetro da circuferencia é ", p)

fimalgoritmo