algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025
var

l1, l2, l3, p: real

inicio
escreval("digite os lados do triangulo")
leia(l1)
leia(l2)
leia(l3)

p <- l1+l2+l3

escreval("o perimetro do seu triangulo é ", p)

fimalgoritmo