algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025
var

n1, n2, q, resto: inteiro

inicio

escreval("digite dois valores inteiros")
leia(n1)
leia(n2)

q <- n1\n2

escreval("o quociente entre os dois valores é ", q) 

resto <- n1 mod n2

escreval("o resto é ", resto)



fimalgoritmo