algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025
var

numero, sucessor: inteiro

inicio

escreval("digite um numero")
leia(numero)

sucessor <- numero + 1

escreval("sucessor é ", sucessor)



fimalgoritmo