algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 02/04/2025 
var

n1, n2, M: real

inicio
escreval("digite as duas notas aluno")
leia(n1)
leia(n2)

M <- (n1+n2)/2

escreval("a nota semestral do aluno é ", M)




fimalgoritmo