algoritmo "Nome do Programa"
// Disciplina  : Gerência de Configuração e Controle de Versão
// Professor   : Anderson Iwazaki
// Descrição   : Projeto Final
// Autor(a)    : Henan Heiiji Shirahige e Mateus Henrique 
// Data atual  : 01/04/2025
var

C, F: caractere

inicio

escreva("Digite o valor da temperatura em graus celsius")
leia(C)
F <- (9*C+160)/5
escreval("Conversor de temperatura")
escreva("A temperatura dada  ́é ", F, "graus Fahrenheit.")

fimalgoritmo